
# conda env create -f requirements.yml

# conda env update -f requirements.yml

# conda env remove --name forecastATM


name: forecastATM
channels:
  - defaults
  - conda-forge    
dependencies:  
  - python = 3.10
  - pip
  - pip:    
    - matplotlib
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch
    - tqdm
